### ISSUE TITLE
Shout at the Devil (1983)

### ISSUE THREAD

**Issue by KarlHeitmann** [KarlHeitmann/taller-github-g-2#2]
Agregar disco

**Comment by patcont** [comment]
Yo quiero este, asegurao.

**Comment by Verastian** [comment]
Este disco yo lo  subiré, Sebastián Vera

**Comment by KarlHeitmann** [comment]
Uhh @patcont llegó primero y lo había dicho por el chat.

**Comment by KarlHeitmann** [comment]
@Verastian , escoge otro disco porfa

**Comment by Verastian** [comment]
escogí otro!! no me fije que ya estaba Patricio jajaj

**Comment by KarlHeitmann** [comment]
Cerrado https://github.com/KarlHeitmann/taller-github-g-2/pull/13
