### ISSUE TITLE
Theatre of Pain (1985)

### ISSUE THREAD

**Issue by KarlHeitmann** [KarlHeitmann/taller-github-g-2#3]
Agregar disco

**Comment by Franciscoj91** [comment]
@KarlHeitmann  Hola Karl, estoy trabajando en este disco, acabo de recordar que tenia que comentar, para que me puedas asignar este disco. Muchas Gracias.

**Comment by KarlHeitmann** [comment]
Cerrado https://github.com/KarlHeitmann/taller-github-g-2/pull/11
