### ISSUE TITLE
Mötley Crüe (1994)

### ISSUE THREAD

**Issue by KarlHeitmann** [KarlHeitmann/taller-github-g-2#6]
Agregar disco

**Comment by Denisse1985** [comment]
Hola!! Soy Denisse, voy con este...

Saludos

**Comment by KarlHeitmann** [comment]
Listo Denisse! Asignada!

**Comment by KarlHeitmann** [comment]
Cerrado https://github.com/KarlHeitmann/taller-github-g-2/pull/17
